AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mini CI/CD Project - VPC, EC2 WebApp (React+Express), EC2 DB (PostgreSQL), CloudWatch, SNS'

Parameters:
  KeyName:
    Description: EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
  
  EmailAddress:
    Description: Email for SNS notifications
    Type: String

  DBPassword:
    Description: Database password
    Type: String
    NoEcho: true
    MinLength: 8

Resources:
  # VPC Configuration
  ProjectVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: ProjectVPC

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: ProjectIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ProjectVPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjectVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet

  # Private Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjectVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet

  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProjectVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Private Route Table
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProjectVPC
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # Security Group for WebApp (Public)
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !Ref ProjectVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: WebAppSG

  # Security Group for Database (Private)
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow PostgreSQL from WebApp only
      VpcId: !Ref ProjectVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: DBSG

  # IAM Role for EC2 CloudWatch
  EC2CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Tags:
        - Key: Name
          Value: EC2CloudWatchRole

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2CloudWatchRole

  # Database EC2 Instance (Private) - PostgreSQL
  DBInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref DBSecurityGroup
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          echo "========================================="
          echo "Starting Database Setup - $(date)"
          echo "========================================="
          
          # Update system
          echo "[1/6] Updating system packages..."
          yum update -y || { echo "Failed to update system"; exit 1; }
          
          # Install PostgreSQL 14
          echo "[2/6] Installing PostgreSQL 14..."
          amazon-linux-extras install postgresql14 -y || { echo "Failed to install PostgreSQL extras"; exit 1; }
          yum install -y postgresql-server postgresql-contrib || { echo "Failed to install PostgreSQL"; exit 1; }
          
          # Initialize PostgreSQL
          echo "[3/6] Initializing PostgreSQL..."
          /usr/bin/postgresql-setup --initdb || { echo "Failed to initialize PostgreSQL"; exit 1; }
          
          # Configure PostgreSQL
          echo "[4/6] Configuring PostgreSQL..."
          sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/pgsql/data/postgresql.conf
          echo "host all all 10.0.0.0/16 md5" >> /var/lib/pgsql/data/pg_hba.conf
          
          # Start PostgreSQL
          echo "[5/6] Starting PostgreSQL service..."
          systemctl start postgresql || { echo "Failed to start PostgreSQL"; exit 1; }
          systemctl enable postgresql
          
          # Wait for PostgreSQL to be ready
          echo "[6/6] Waiting for PostgreSQL to be ready..."
          sleep 15
          
          # Create database and user
          echo "Creating database and user..."
          sudo -u postgres psql <<EOF
          CREATE DATABASE taskflow_db;
          CREATE USER taskflow_user WITH ENCRYPTED PASSWORD '${DBPassword}';
          GRANT ALL PRIVILEGES ON DATABASE taskflow_db TO taskflow_user;
          \c taskflow_db
          GRANT ALL ON SCHEMA public TO taskflow_user;
          EOF
          
          echo "========================================="
          echo "Database Setup Complete - $(date)"
          echo "========================================="
      Tags:
        - Key: Name
          Value: DBInstance

  # WebApp EC2 Instance (Public) - Node.js + React
  WebAppInstance:
    Type: AWS::EC2::Instance
    DependsOn: DBInstance
    Properties:
      InstanceType: t3.small
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          echo "========================================="
          echo "Starting WebApp Setup - $(date)"
          echo "========================================="
          
          # Update system
          echo "[1/10] Updating system packages..."
          yum update -y || { echo "Failed to update system"; exit 1; }
          
          # Install Git
          echo "[2/10] Installing Git..."
          yum install -y git || { echo "Failed to install Git"; exit 1; }
          git --version || { echo "Git installation verification failed"; exit 1; }
          
          # Install Node.js 20 LTS using NVM (compatible with Amazon Linux 2)
          echo "[3/10] Installing Node.js 20 LTS..."
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash || { echo "Failed to download NVM"; exit 1; }
          
          # Load NVM
          export NVM_DIR="/root/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          # Install Node.js 20 (LTS - compatible with Amazon Linux 2)
          nvm install 20 || { echo "Failed to install Node.js 20"; exit 1; }
          nvm use 20
          nvm alias default 20
          
          # Make node and npm available globally
          ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/node" /usr/local/bin/node
          ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/npm" /usr/local/bin/npm
          ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/npx" /usr/local/bin/npx
          
          # Verify Node.js installation
          node --version || { echo "Node.js installation verification failed"; exit 1; }
          npm --version || { echo "NPM installation verification failed"; exit 1; }
          echo "Node.js $(node --version) installed successfully!"
          
          # Install PM2 globally
          echo "[4/10] Installing PM2..."
          npm install -g pm2 || { echo "Failed to install PM2"; exit 1; }
          
          # Make PM2 available globally
          ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" /usr/local/bin/pm2
          
          pm2 --version || { echo "PM2 installation verification failed"; exit 1; }
          
          # Install Nginx
          echo "[5/10] Installing Nginx..."
          amazon-linux-extras install nginx1 -y || { echo "Failed to install Nginx"; exit 1; }
          
          # Create app directory
          echo "[6/10] Creating application directory..."
          mkdir -p /opt/webapp
          chown -R ec2-user:ec2-user /opt/webapp
          
          # Create deployment script
          echo "[7/10] Creating deployment script..."
          cat > /opt/webapp/deploy.sh <<'DEPLOYEOF'
          #!/bin/bash -e
          cd /opt/webapp
          
          # Install dependencies
          if [ -f "package.json" ]; then
            npm install
          fi
          
          # Build frontend if exists
          if [ -d "client" ]; then
            cd client
            npm install
            npm run build
            cd ..
          fi
          
          # Start backend with PM2
          pm2 delete taskflow-api 2>/dev/null || true
          pm2 start server/index.js --name taskflow-api
          pm2 save
          DEPLOYEOF
          
          chmod +x /opt/webapp/deploy.sh
          chown ec2-user:ec2-user /opt/webapp/deploy.sh
          
          # Configure Nginx
          echo "[8/10] Configuring Nginx..."
          cat > /etc/nginx/conf.d/webapp.conf <<'NGINXEOF'
          server {
              listen 80;
              server_name _;
              
              # Serve React frontend (Vite uses 'dist' directory)
              location / {
                  root /opt/webapp/client/dist;
                  try_files $uri $uri/ /index.html;
                  add_header Cache-Control "no-cache, must-revalidate";
              }
              
              # Proxy API requests to Express
              location /api {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          NGINXEOF
          
          # Start Nginx
          echo "[9/10] Starting Nginx..."
          systemctl start nginx || { echo "Failed to start Nginx"; exit 1; }
          systemctl enable nginx
          
          # Create environment file
          echo "[10/10] Creating environment configuration..."
          cat > /opt/webapp/.env <<ENVEOF
          DB_HOST=${DBInstance.PrivateIp}
          DB_PORT=5432
          DB_NAME=taskflow_db
          DB_USER=taskflow_user
          DB_PASSWORD=${DBPassword}
          NODE_ENV=production
          PORT=3000
          ENVEOF
          
          chown ec2-user:ec2-user /opt/webapp/.env
          
          # Install CloudWatch agent
          echo "Installing CloudWatch agent..."
          wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm || { echo "Failed to download CloudWatch agent"; exit 1; }
          rpm -U ./amazon-cloudwatch-agent.rpm || { echo "Failed to install CloudWatch agent"; exit 1; }
          
          # Configure CloudWatch agent
          cat > /opt/aws/amazon-cloudwatch-agent/etc/config.json <<'CWEOF'
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/nginx/access.log",
                      "log_group_name": "/aws/ec2/webapp",
                      "log_stream_name": "{instance_id}/nginx-access"
                    },
                    {
                      "file_path": "/var/log/nginx/error.log",
                      "log_group_name": "/aws/ec2/webapp",
                      "log_stream_name": "{instance_id}/nginx-error"
                    },
                    {
                      "file_path": "/var/log/user-data.log",
                      "log_group_name": "/aws/ec2/webapp",
                      "log_stream_name": "{instance_id}/user-data"
                    }
                  ]
                }
              }
            },
            "metrics": {
              "namespace": "WebApp/Performance",
              "metrics_collected": {
                "cpu": {
                  "measurement": [
                    {"name": "cpu_usage_idle", "rename": "CPU_IDLE", "unit": "Percent"}
                  ],
                  "totalcpu": false
                },
                "mem": {
                  "measurement": [
                    {"name": "mem_used_percent", "rename": "MEM_USED", "unit": "Percent"}
                  ]
                }
              }
            }
          }
          CWEOF
          
          # Start CloudWatch agent
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
            -a fetch-config -m ec2 -s \
            -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json || { echo "Failed to start CloudWatch agent"; exit 1; }
          
          echo "========================================="
          echo "WebApp Setup Complete - $(date)"
          echo "========================================="
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "PM2 version: $(pm2 --version)"
          echo "Git version: $(git --version)"
          echo "========================================="
      Tags:
        - Key: Name
          Value: WebAppInstance

  # Elastic IP for WebApp
  WebAppEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref WebAppInstance
      Tags:
        - Key: Name
          Value: WebApp-EIP

  # SNS Topic for Alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: WebApp-Alerts
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email

  # CloudWatch Alarm - High CPU
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: WebApp-High-CPU
      AlarmDescription: Alert when CPU exceeds 70%
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref WebAppInstance
      AlarmActions:
        - !Ref AlertTopic

  # CloudWatch Alarm - High Memory
  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: WebApp-High-Memory
      AlarmDescription: Alert when memory usage exceeds 80%
      MetricName: MEM_USED
      Namespace: WebApp/Performance
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic

  # CloudWatch Log Group
  WebAppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ec2/webapp
      RetentionInDays: 7

Outputs:
  WebAppURL:
    Description: WebApp Public URL
    Value: !Sub 'http://${WebAppEIP}'
    Export:
      Name: WebAppURL

  WebAppPublicIP:
    Description: WebApp Public IP (Elastic IP)
    Value: !Ref WebAppEIP

  WebAppElasticIPAllocation:
    Description: Elastic IP Allocation ID
    Value: !GetAtt WebAppEIP.AllocationId

  DBPrivateIP:
    Description: Database Private IP
    Value: !GetAtt DBInstance.PrivateIp

  SNSTopicARN:
    Description: SNS Topic ARN for alerts
    Value: !Ref AlertTopic

  VPCId:
    Description: VPC ID
    Value: !Ref ProjectVPC
    Export:
      Name: ProjectVPCId
