AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal test to identify the issue'

Parameters:
  KeyName:
    Type: String
    Default: taskflow-key

Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true

  TestSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TestVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  TestSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Test SG
      VpcId: !Ref TestVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  TestInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref TestSubnet
      SecurityGroupIds:
        - !Ref TestSG
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'

Outputs:
  InstanceId:
    Value: !Ref TestInstance
